### PR TITLE
Update source code to later versions of Nim.

### PR DESCRIPTION
**Pull request by kritoke**
Updated some of the source code to use non-depreciated procedure calls.  Updated the < and time related syntax to updated calls that work in newer versions of Nim.

### CODE REVIEW

**Comment by dom96** [comment]
Thank you for this. I do wonder however whether the most easily accessible version of this code should diverge from the book or whether I should introduce a new branch for these changes.

**Comment by kritoke** [comment]
Good question, maybe provide info in the Readme to the branch? When folks google this, they could probably run across the branch maybe?  Wonder what other authors do in situations like this.

**Comment by narimiran** [comment]
> whether I should introduce a new branch for these changes

If I were a reader of your book and went on Github to copy/paste your code into my editor so I can try it out on my own (with my current Nim version), I would expect it to be a straight-forward thing to do, i.e. that I shouldn't realize that there are multiple branches and the code I want is in some non-default branch.

**Comment by dom96** [comment]
Merged into https://github.com/dom96/nim-in-action-code/tree/v1.2.6. Thanks!

**Pull request closed without merging**
